# Generated by Django 2.1.3 on 2018-11-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfriends', '0002_auto_20181127_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_accepted',
        ),
    ]
